qawolf/qawolf

- bin/test.template
- src/browser/hooks.ts
- src/build/__snapshots__/buildTest.test.ts.snap
- src/config.ts
remove describe wrapper in test.template
> add SLEEP_AFTER_EACH env variable

- .env
- .github/workflows/test.yml
- src/browser/Browser.test.ts
- src/browser/Browser.ts
- src/browser/RequestTracker.test.ts
- src/browser/RequestTracker.ts
- src/browser/browserUtils.ts
- src/browser/pageUtils.ts
- src/browser/runStep.test.ts
Resolves https://github.com/qawolf/qawolf/issues/57
> RequestTracker

- src/build/buildSteps.test.ts
- src/build/buildSteps.ts
* We now use puppeteer click so this seems a purer mapping 
* Records enter press in a form as a click on the submit button, so now we are including these in our tests
> Change isMouseDown -> isClick

- package-lock.json
- package.json
- packages/browser/package.json
- packages/build-job/package.json
- packages/build-test/package.json
- packages/jest-environment/package.json
- packages/runner/package.json
- add jest as a devDependency to all packages so you can run npm run test in each directory
re ignore-scripts: https://github.com/lerna/lerna/issues/1855
> bootstrap: --hoist to share dependencies and do not --ignore-scripts so puppeteer gets installed

- package-lock.json
- package.json
- packages/browser/package-lock.json
- packages/browser/src/browserUtils.ts
- packages/build-job/package-lock.json
- packages/build-test/package-lock.json
- packages/jest-environment/package-lock.json
- packages/runner/package-lock.json
- --hoist can cause problems when installing outside of lerna
- manually run install:puppeteer so we can --ignore-scripts
> add back --ignore-scripts to bootstrap and remove --hoist

- packages/build-test/src/buildTest.ts
- packages/build-test/tests/__snapshots__/buildTest.test.ts.snap
- packages/build-test/tests/buildTest.test.ts
* Include quotes and truncate at 40 instead of 20 characters
> Improve test name code

- .github/actions/local-docker/action.yml
- .github/workflows/npm-test.yml
- action.yml
- separate local docker action
> setup qawolf action to user dockerhub for speed

- packages/web/src/element.ts
* Use html of all svg icon children rather than just path
> Update icon content for svg to be more generic

- packages/browser/src/QAWolfPage.ts
- packages/cli/src/runTest.ts
- packages/jest-environment/src/RunnerEnvironment.ts
- packages/logger/src/Logger.ts
- packages/logger/src/index.ts
- packages/screen/src/createGif.ts
- packages/web/src/match.ts
- packages/web/src/scrollElement.ts
- name log files by the test name
> Capture browser logs

- packages/browser/src/actions.ts
- packages/browser/tests/actions/scroll.test.ts
- packages/browser/tests/web/Recorder.test.ts
- packages/build-test/src/buildTest.ts
- packages/build-test/tests/__snapshots__/buildTest.test.ts.snap
- packages/jest-environment/src/RunnerEnvironment.ts
- packages/jest-environment/src/types.ts
- packages/jest-environment/tests/RunnerEnvironment.test.ts
- packages/runner/src/Runner.ts
- packages/web/src/index.ts
- packages/web/src/scroll.ts
its just more consistent and sounds better
> rename scrollElement -> scroll

- packages/browser/tests/actions/scroll.test.ts
- packages/web/src/scroll.ts
Resolves https://github.com/qawolf/qawolf/issues/112
> only error scrolling when we cannot scroll at all

- packages/build-workflow/package-lock.json
- packages/cli/package.json
- packages/cli/src/githubAction.ts
- packages/cli/src/index.ts
- packages/cli/src/record.ts
- packages/cli/tsconfig.package.json
- packages/github/package.json
- packages/github/src/buildAction.ts
- packages/github/src/index.ts
- packages/github/static/action.hbs
- packages/github/tests/__snapshots__/buildAction.test.ts.snap
- packages/github/tests/buildAction.test.ts
- packages/github/tests/buildMarkdown.test.ts
> CLI command to generate GitHub Action

- packages/browser/src/actions.ts
- packages/browser/tests/actions/select.test.ts
- packages/web/src/index.ts
- packages/web/src/select.ts
- packages/web/src/wait.ts
> Wait for option with specified value in select

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/index.ts
Continuing https://github.com/qawolf/qawolf/pull/140/files
> Warn for unknown commands

- packages/cli/src/index.ts
> feat(cli): warn appropriately if an unknown command was supplied

- packages/cli/src/index.ts
closes #145 
- Introduces new `--version` flag.
> feat(cli): show version information

- packages/cli/src/index.ts
> fix(cli): Fixed misleading usage information

- README.md
- packages/README.md
Will add how it works later but this is a good technical overview in the meantime
> add packages/README.md

- packages/browser/tests/web/element.test.ts
- packages/browser/tests/web/find.test.ts
- packages/build-workflow/package.json
- packages/build-workflow/src/buildClickSteps.ts
- packages/build-workflow/tsconfig.package.json
- packages/web/src/Recorder.ts
- packages/web/src/element.ts
- packages/web/src/find.ts
Closes #129
Find highest clickable ancestor (stopping at closest w/ data attribute) and use that as the click target.
> 👴Clickable ancestors

- packages/github/static/action.hbs
- packages/github/tests/__snapshots__/buildAction.test.ts.snap
> Fix spacing in GitHub Actions workflow file

- packages/browser/src/keyboard.ts
- packages/cli/src/test.ts
- packages/runner/src/Runner.ts
- packages/web/src/find.ts
- packages/web/src/xpath.ts
continuation of https://github.com/qawolf/qawolf/pull/170
> chore: minor code refactoring

- packages/browser/tests/web/element.test.ts
- packages/web/src/element.ts
> Include child image src and alt

- packages/build-workflow/package.json
- packages/build-workflow/src/buildClickSteps.ts
- packages/build-workflow/tests/__snapshots__/buildClickSteps.test.ts.snap
- packages/build-workflow/tests/buildClickSteps.test.ts
- packages/web/src/event.ts
- packages/web/src/index.ts
> ⏭️ Only skip click on input if we type next

- README.md
- packages/cli/src/ci.ts
- packages/cli/src/index.ts
- packages/cli/static/gitlab.yml
> qawolf gitlab command

- .github/workflows/docker-publish.yml
- package-lock.json
- packages/browser/tests/web/compare.test.ts
- packages/build-test/src/formatIt.ts
- packages/build-test/tests/__snapshots__/buildTest.test.ts.snap
- packages/build-test/tests/formatIt.test.ts
- packages/build-test/tests/formatStep.test.ts
- packages/web/src/find/compare.ts
- packages/web/src/serialize.ts
And deploy tags https://github.com/qawolf/qawolf/issues/207
> Fix inner text attribute

- packages/browser/src/strokes.ts
- packages/browser/tests/strokes.test.ts
- packages/browser/tests/web/Recorder.test.ts
- packages/build-test/src/formatMethod.ts
- packages/build-test/src/formatStep.ts
- packages/build-test/tests/__snapshots__/buildTest.test.ts.snap
- packages/build-test/tests/__snapshots__/formatStep.test.ts.snap
- packages/build-workflow/tests/__snapshots__/buildSteps.test.ts.snap
- packages/build-workflow/tests/__snapshots__/buildTypeSteps.test.ts.snap
- packages/jest-environment/src/RunnerEnvironment.ts
- packages/jest-environment/src/types.ts
- packages/jest-environment/tests/RunnerEnvironment.test.ts
- packages/runner/src/Runner.ts
- packages/runner/src/getEnvValues.ts
- packages/runner/tests/Runner.test.ts
- packages/runner/tests/getEnvValues.test.ts
- packages/types/src/index.ts
- packages/web/src/lang.ts
- packages/web/src/serialize.ts
> ✏️Inline values in test

- packages/browser/src/Browser.ts
- packages/browser/tests/Browser.test.ts
> 🐛currentPage should not choose a closed page

- packages/browser/src/browser/launch.ts
- packages/browser/src/keyboard/simplifyStrokes.ts
- packages/browser/tests/keyboard/simplifyStrokes.test.ts
- packages/cli/src/record.ts
- packages/qawolf/package.json
- packages/qawolf/src/index.ts
- packages/qawolf/tsconfig.package.json
- export qawolf.sleep, qawolf.waitFor, qawolf.waitUntil
- launch(options): extend puppeteer.LaunchOptions
- do not timeout when recording
- simplifyStrokes: support any shift key
> Export missing helpers, fix small bugs

- packages/browser/src/find/findCss.ts
- packages/browser/src/find/findText.ts
- packages/browser/src/find/hasText.ts
- packages/browser/tests/find/findText.test.ts
- packages/browser/tests/find/hasText.test.ts
- packages/web/src/find/findText.ts
- packages/web/src/find/hasText.ts
- findCss & findText: store last find on window.qaw_find for easy debugging
- hasText: add logging
- hasText: add test for case sensitivity
> findText: find the best matching element and make it case sensitive

- packages/web/src/element.ts
- packages/web/src/find/findHtml.ts
- packages/web/src/find/findText.ts
- packages/web/src/find/query.ts
- packages/web/src/xpath.ts
- it was mistyped to be HTMLElement[] leading to bugs
> fix queryElements type to be Element

- docs/docs/api.md
- packages/build-code/src/formatIt.ts
- packages/build-code/tests/__snapshots__/formatStep.test.ts.snap
- packages/build-code/tests/formatIt.test.ts
- packages/build-code/tests/formatStep.test.ts
Resolves https://github.com/qawolf/qawolf/issues/236
> Escape single quote characters in test name

- docs/docs/api.md
- docs/docs/edit_your_code.md
Resolves https://github.com/qawolf/qawolf/issues/182
> 🇹How to use Typescript 

- docs/docs/api.md
- packages/browser/src/actions/clearElement.ts
- packages/browser/src/actions/index.ts
- packages/browser/src/actions/typeElement.ts
- packages/browser/tests/actions/clearElement.test.ts
- packages/browser/tests/actions/type.test.ts
- packages/build-workflow/src/buildClickSteps.ts
- packages/build-workflow/tests/__snapshots__/buildClickSteps.test.ts.snap
- packages/build-workflow/tests/__snapshots__/buildSteps.test.ts.snap
- packages/types/src/common.ts
Fixes https://github.com/qawolf/qawolf/issues/245
- add type.options.skipClear
> Do not skip click before type events

- packages/browser/src/keyboard/serializeStrokes.ts
- packages/browser/tests/keyboard/serializeStrokes.test.ts
- packages/build-workflow/package.json
> Increase hot key held threshold to 500ms

- packages/cli/src/runTest.ts
Fixes https://github.com/qawolf/qawolf/issues/270
> override transform to prevent using external babel-jest

- docs/docs/api.md
- packages/browser/src/browser/device.ts
- packages/browser/src/browser/launch.ts
- packages/browser/src/index.ts
- packages/browser/tests/browser/device.test.ts
- packages/browser/tests/browser/launch.test.ts
- packages/browser/tests/docker/launch.test.ts
- packages/qawolf/src/index.ts
- packages/types/src/workflow.ts
- packages/web-tests/tests/element.test.ts
- packages/web-tests/tests/isSelectValueAvailable.test.ts
- packages/web-tests/tests/query.test.ts
- packages/web-tests/tests/serialize.test.ts
Resolves https://github.com/qawolf/qawolf/issues/148
> Expose launch options.device and options.size

- docs/docs/api.md
- docs/docs/cli.md
- packages/browser/src/browser/device.ts
- packages/browser/src/browser/launch.ts
- packages/browser/tests/browser/device.test.ts
- packages/browser/tests/browser/launch.test.ts
- packages/browser/tests/docker/launch.test.ts
- packages/build-code/src/buildCode.ts
- packages/build-code/src/formatLaunch.ts
- packages/build-code/static/script.hbs
- packages/build-code/static/test.hbs
- packages/build-code/tests/__snapshots__/buildCode.test.ts.snap
- packages/build-code/tests/buildCode.test.ts
- packages/build-code/tests/formatLaunch.test.ts
- packages/build-workflow/src/buildWorkflow.ts
- packages/cli/src/index.ts
- packages/cli/src/record.ts
- packages/types/src/workflow.ts
- packages/web-tests/tests/compare.test.ts
- packages/web/src/find/compare.ts
> qawolf record --device "iPhone 7"

- docs/docs/contribute.md
- docs/docs/get_started.md
> Fix record command in Get Started doc and add section on contributing to docs

- README.md
- docs/docs/api.md
- docs/docs/cli.md
- docs/docs/create_a_test.md
- docs/docs/edit_test_code.md
- docs/docs/emulate_a_device.md
- docs/docs/faq.md
- docs/docs/how_it_works.md
- docs/docs/introduction.md
- docs/docs/quick_start.mdx
- docs/docs/review_test_code.md
- docs/docs/set_up_ci.md
- docs/docs/test_different_devices.md
- docs/docs/use_typescript.md
- docs/sidebars.js
- docs/src/components/GetStarted.js
> Test Different Devices doc

- docs/docs/api.md
- docs/docs/cli.md
- docs/docs/create_a_test.md
- docs/docs/edit_test_code.md
- docs/docs/emulate_a_device.md
- docs/docs/quick_start.mdx
- docs/docs/run_a_test_locally.md
- docs/src/components/GetStarted.js
- packages/cli/src/create.ts
- packages/cli/src/index.ts
> Rename qawolf record -> qawolf create

- packages/browser/src/find/find.ts
- packages/browser/src/find/findCss.ts
- packages/browser/src/find/findHtml.ts
- packages/browser/src/find/findText.ts
- packages/browser/src/page/QAWolfPage.ts
- packages/browser/tests/find/findHtml.test.ts
- packages/build-code/src/index.ts
- packages/build-code/src/stepToSelector.ts
- packages/cli/src/create.ts
- packages/types/src/selector.ts
- packages/types/src/workflow.ts
- packages/web/src/find/findCss.ts
- packages/web/src/find/findHtml.ts
- packages/web/src/find/findText.ts
- packages/web/src/index.ts
- packages/web/src/serialize.ts
- rename serializeStep -> stepToSelector -- remove StepSerialized instead output Selector
- combine htmlSelectorToDocSelector into deserializeDocSelector
- move action from Selector -> FindElementOptions
Prep work for #292
> change Selector to be a union type

- docs/docs/api.md
- docs/docs/introduction.md
- docs/docs/use_a_test_attribute.md
- docs/docs/use_typescript.md
- docs/sidebars.js
> Tutorial: Use a test attribute

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/index.ts
> feat(cli): Notify users if an update is available

- packages/build-code/src/formatIt.ts
- packages/build-code/static/script.hbs
- packages/build-code/static/test.hbs
- packages/build-code/tests/__snapshots__/buildCode.test.ts.snap
- packages/build-code/tests/__snapshots__/formatStep.test.ts.snap
- packages/build-code/tests/formatIt.test.ts
> 💬Add comments to generated script code

- packages/browser/src/browser/QAWolfBrowser.ts
- packages/cli/src/index.ts
- packages/cli/src/runJest.ts
- packages/cli/tests/runJest.test.ts
> Fix qawolf test exit code

- .github/workflows/npm-test-ubuntu.yml
- .github/workflows/npm-test-windows.yml
- packages/cli/package-lock.json
- packages/cli/src/runJest.ts
- packages/qawolf/package-lock.json
> runJest: override config

- package-lock.json
- package.json
- packages/browser/src/browser/launchPuppeteer.ts
- packages/screen/package-lock.json
- packages/screen/package.json
- packages/screen/src/ffmpeg.ts
> use slimmer @qawolf/ffmpeg-static

- README.md
- docs/docs/cli.md
- docs/docs/quick_start.mdx
- docs/docs/set_up_ci.md
- docs/src/components/SetUpCI.js
- packages/cli/src/ci.ts
- packages/cli/src/index.ts
- packages/cli/static/jenkins.hbs
> Add "npx qawolf jenkins"

- package.json
- Included `lint:fix` script to autofix lint issues.
- Updated `lint-staged` config to autofix lint issues and stage the respective files.
> chore: Updated lint-staged config

- docs/docs/api.md
- packages/browser/src/browser/QAWolfBrowser.ts
> 😴Sleep before close

- docs/docs/api.md
- docs/docs/cli.md
- docs/docs/edit_test_code.md
- docs/docs/review_test_code.md
- docs/docs/use_a_test_attribute.md
- packages/build-code/src/stepToSelector.ts
- packages/build-code/tests/formatMethod.test.ts
- packages/build-code/tests/stepToSelector.test.ts
- packages/config/src/config.ts
Resolves #299
- default QAW_ATTRIBUTE = "data-qa,data-test,data-testid"
> QAW_ATTRIBUTE: support multiple attributes

- docs/docs/cli.md
- packages/cli/src/create.ts
- packages/cli/src/index.ts
- packages/cli/src/runJest.ts
- packages/cli/src/utils.ts
- packages/cli/tests/runJest.test.ts
resolves #332
Added path option to cli.
QA Wolf is a great product. Thanks☺️
> feat(cli): Add path option

- packages/screen/package-lock.json
- packages/screen/package.json
> download compressed ffmpeg

- .github/workflows/npm-test-windows.yml
- package.json
> Fix windows tests

- packages/web-tests/tests/element.test.ts
- packages/web/src/element.ts
> fix getClickableAncestor to work for multiple attributes

- docs/docs/api.md
- packages/browser/src/browser/launch.ts
- packages/browser/src/browser/launchPuppeteer.ts
- packages/browser/tests/full/VirtualCapture.test.ts
- packages/config/src/config.ts
- packages/screen/package-lock.json
- packages/screen/package.json
- packages/screen/src/CiInfoTypes.ts
- packages/screen/src/VirtualCapture.ts
> Record local docker

- README.md
- docs/docs/api/environment_variables.md
> add gif to README

- packages/browser/src/actions/clearElement.ts
- packages/browser/tests/actions/clearElement.test.ts
> fix: clear content editable

- packages/browser/src/context/QAWolfBrowserContext.ts
- packages/browser/tests/context/BrowserContext.test.ts
> 📹Capture after activating first page

- packages/cli/src/runJest.ts
> 🐛Allow passing --config to qawolf test

- packages/build-code/src/buildInitialCode.ts
- packages/build-code/tests/__snapshots__/buildInitialCode.test.ts.snap
> ♻️Add browser argument and export script method

- packages/web-tests/tests/buildCssSelector.test.ts
- packages/web/src/buildCssSelector.ts
> buildCssSelector: target the clickable descendant

- docs/docs/api/browser_context/click.mdx
- docs/docs/api/browser_context/type.mdx
- docs/docs/api/components/ArgumentFindElementOptions.js
- docs/docs/api/components/ArgumentRepl.js
- docs/docs/api/components/ArgumentTest.js
- docs/docs/api/qawolf/repl.mdx
- docs/docs/api/table_of_contents.md
- docs/docs/contribute.md
- docs/docs/use_custom_selectors.md
- docs/docs/use_the_repl.md
- docs/sidebars.js
> Update docs for release

- packages/browser/src/actions/selectElementContent.ts
- packages/browser/src/actions/typeElement.ts
- packages/browser/src/retry.ts
- packages/browser/tests/actions/type.test.ts
- packages/build-code/src/buildDescription.ts
- packages/build-code/tests/buildDescription.test.ts
click sometimes puts it in the middle
> type: move caret to end of text input

- package.json
- sandbox/package-lock.json
- sandbox/package.json
- sandbox/src/App.js
- sandbox/src/pages/NestedDataAttributes/RadioGroup.js
- sandbox/src/pages/NestedDataAttributes/index.js
- sandbox/src/pages/RadioInputs/HtmlRadioInputs.js
- src/web/buildCssSelector.ts
- test/create-code/ContextEventCollector.test.ts
- test/web/buildCssSelector.test.ts
> Include ancestor data attributes if selector not unique

- src/web/buildCssSelector.ts
- test/create-code/ContextEventCollector.test.ts
- test/web/buildCssSelector.test.ts
> Add regex support to attribute

- .github/workflows/unit-tests.yml
- package-lock.json
- package.json
- src/build-code/Expression.ts
- src/index.ts
- test/build-code/Expression.test.ts
- test/create-code/create.test.ts
- test/utils.ts
> Create playwright-utils scroll action

- src/build-code/buildTemplate.ts
- test/build-code/__snapshots__/buildTemplate.test.ts.snap
- test/build-code/buildTemplate.test.ts
> Handle invalid script names

- docs/docs/api/qawolf/repl.mdx
- docs/docs/components/BrowserTabs.js
- docs/docs/components/CiArtifacts.mdx
- docs/docs/components/CiTabs.js
- docs/docs/components/PackageManagerTabs.js
- docs/docs/create_a_test.md
- docs/docs/install.mdx
- docs/docs/run_tests_in_ci.mdx
- docs/docs/run_tests_locally.mdx
- docs/docs/what_is_qa_wolf.md
Still some TODOs, but did the best I can for now
* relates to #468
> Update Get Started docs

- src/cli/cli.ts
- src/cli/run.ts
- default `npx qawolf test` to headed, add --headless flag
- allow passing --url and --name to create. resolves #493
> Improve cli

- src/index.ts
> Set qawolf on repl context

- packages/create-qawolf/package-lock.json
- packages/create-qawolf/package.json
- packages/create-qawolf/src/cli.ts
- packages/create-qawolf/src/config.ts
- packages/create-qawolf/src/packageJson.ts
- packages/create-qawolf/test/cli.test.ts
- packages/create-qawolf/test/config.test.ts
- packages/create-qawolf/test/packageJson.test.ts
Resolves #536
- use latest inquirer and add test to prompt
- do not use fs.promises (remove ExperimentalWarning log)
> add tests for prompt to make sure node 10.x works

- src/build-code/buildTemplate.ts
- src/cli/saveTemplate.ts
- test/cli/saveTemplate.test.ts
> TemplateFunction allow returning promise

- .github/workflows/create-qawolf.yml
- .github/workflows/qawolf-linux.yml
- package-lock.json
- package.json
- test/.qawolf/scroll.test.ts
- test/.qawolf/utils.js
- test/browser.ts
- test/cli/CDPSession.ts
- test/cli/__snapshots__/create.e2e.test.ts.snap
- test/cli/create.e2e.test.ts
- test/cli/test.e2e.test.ts
- test/fixtures/config.ts
- test/run/runTests.test.ts
- tsconfig.json
> ✅Replace flaky create end-to-end test

- packages/sandbox/src/pages/CheckboxInputs/HtmlCheckboxInputs.js
- src/build-workflow/buildClickSteps.ts
- src/types.ts
- src/web/PageEventCollector.ts
- src/web/buildCssSelector.ts
- src/web/element.ts
- test/web/element.test.ts
> Ignore click events on elements that are not visible

- docs/docs/api/cli.mdx
- docs/docs/api/config.mdx
- docs/docs/api/environment_variables.md
- docs/docs/api/table_of_contents.md
- docs/docs/use_custom_selectors.md
- docs/docs/what_is_qa_wolf.md
- src/config.ts
- test/cli/create.e2e.test.ts
One way to do things: qawolf.config.js
> Remove QAW_ATTRIBUTE environment variable

- src/run/buildEditOptions.ts
- test/run/buildEditOptions.test.ts
> Change watch -> watchAll

- docs/docs/add_assertions.md
- js-jest.config.json
- package-lock.json
- package.json
- test/.qawolf/scroll.test.ts
- ts-jest.config.json
> Include expect-playwright

- docs/docs/api/table_of_contents.md
- expect-playwright.js
- js-jest.config.json
- package.json
- ts-jest.config.json
jest will not find a module that is a dependency of another module
> re-export expect-playwright

- docs/docs/api/components/cli/ArgumentCreate.js
- docs/docs/emulate_a_device.md
> Add note about Windows PowerShell in emulate a device docs

- src/config.ts
- src/create-code/ContextEventCollector.ts
- src/create-code/CreateManager.ts
- src/web/PageEventCollector.ts
- test/config.test.ts
- test/create-code/ContextEventCollector.test.ts
- test/saveFixture.ts
- simplify ContextEventCollector options
> PageEventCollector: make attribute optional

- js-jest.config.json
- ts-jest.config.json
- fixes #666 
- how to disable just from reading babel from [jest docs](https://jestjs.io/docs/en/getting-started#using-babel)
> remove babel transform

- docs/docs/api/qawolf/wait_for_page.mdx
- src/utils/context/waitForPage.ts
- test/create-code/createPrompt.test.ts
- test/utils/context/waitForPage.test.ts
- test/utils/repl/addScreenshotCommand.test.ts
> feat: waitForPage bring the page to the front

- src/build-workflow/event.ts
- src/types.ts
- src/web/PageEventCollector.ts
- test/create-code/ContextEventCollector.test.ts
- test/fixtures/fillTextInput.json
- test/fixtures/pressTabWithTextInputFocus.json
- test/fixtures/textInputsSelectAll.json
- test/utils.ts
This is no longer used since we always fill inputs
> fix: remove unused selectall event

- src/build-workflow/buildClickSteps.ts
- src/web/PageEventCollector.ts
- test/build-workflow/__snapshots__/buildClickSteps.test.ts.snap
- test/build-workflow/__snapshots__/buildSteps.test.ts.snap
- test/build-workflow/buildClickSteps.test.ts
- test/fixtures/searchGoogle.json
Resolves #779
This could happen if selector generation is really slow (which should be rare now)
> fix: duplicate click actions when click is >300ms later

- docs/docs/api/components/qawolf/ArgumentAssertElementText.js
- docs/docs/api/qawolf/assert_element_text.mdx
- docs/docs/api/qawolf/scroll.mdx
- docs/docs/api/table_of_contents.md
- docs/sidebars.js
- src/qawolf.ts
- src/utils/index.ts
- src/utils/page/assertText.ts
- src/utils/page/scroll.ts
- test/utils/page/assertText.test.ts
> Assert that an element has text

- src/build-code/buildStepLines.ts
- test/build-code/buildStepLines.test.ts
* relates to #788 
I am checking the tests and fixing if needed before merging this. Thanks @gandie! 🙌
> Use waiting selector method instead of $ method to get iframe handle

- README.md
- package-lock.json
- package.json
- packages/sandbox/package-lock.json
- packages/sandbox/package.json
- packages/sandbox/src/pages/Buttons/HtmlButtons.js
- src/build-code/buildStepLines.ts
- src/build-code/buildVirtualCode.ts
- src/create-code/ContextEventCollector.ts
- src/types.ts
- test/build-code/buildStepLines.test.ts
- test/create-code/ContextEventCollector.test.ts
> fix: get a new frame after a navigation

- src/web/isDynamic.ts
- test/web/isDynamic.test.ts
add test case for haSfzA ("ha", "sfz", "a")
> fix: make isDynamic more strict by removing alphabet from word list

- docs/docs/api/cli.mdx
- docs/docs/configure_qa_wolf.mdx
- docs/docs/create_a_test.mdx
- docs/docs/edit_a_test.md
- docs/docs/emulate_a_device.md
- docs/docs/handle_sign_in.md
- qawolf.config.js
- src/build-code/buildTemplate.ts
- test/build-code/__snapshots__/buildTemplate.test.ts.snap
- test/build-code/buildTemplate.test.ts
- test/cli/__snapshots__/create.e2e.test.ts.snap
- fix: waitUntil "domcontentloaded" by default
Resolves #828, #831
> fix: move browser creation/teardown into test for default template

- src/web/isDynamic.ts
- test/web/isDynamic.test.ts
Relates to https://github.com/qawolf/qawolf/pull/835
I am sure this is possible to do in one regex, but I gave up trying. 🤷
> fix: isDynamic

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/enhancement.md
I don't think there's any way to preview before merging into the default branch. But you can review markdown here, and we can do a quick fix after merging if anything doesn't look/work right.
> chore: issue templates

- runner/Dockerfile
Resolves #894
Let's add each language as users request them, instead of adding a bunch of fonts no one uses.
> 🌎 add chinese font

- app/lib/helpers.ts
- app/server/resolvers/run.ts
- app/test/lib/helpers.test.ts
* resolves #900 
* resolves #901
> Support case sensitive URLs and URLs with colons

- app/components/Editor/hooks/browser.ts
- app/components/Editor/hooks/connectRunner.ts
- app/lib/runner.ts
> Fix browser reconnection issues

- app/server/schema.graphql
- runner/src/services/api.ts
> runner: load helpers for runs

- app/server/models/runner.ts
- app/server/resolvers/runner.ts
We expect this to happen when the runner is deleted
> updateRunnerResolver: handle runner not found

- app/components/Editor/hooks/connectRunner.ts
- app/components/Editor/hooks/logs.ts
Regression from https://github.com/qawolf/qawolf/pull/941
Thanks 🐺 end-to-end tests :)
> fix: logs not connecting

- app/components/Docs/docs.ts
- app/pages/docs/call-an-api.mdx
> Docs: Call an API

- app/components/Editor/hooks/runProgress.ts
- app/components/UserContext.tsx
- app/hooks/mutations.ts
* addresses issue where Sentry user not initialized if already logged in
* fixes run id missing from logs
> Sentry fixes

- app/components/Editor/Sidebar/HelpersEditor.tsx
> Do not overwrite helpers if team not loaded

- app/components/shared-new/AppButton/index.tsx
- app/components/shared-new/Select/Option.tsx
Move active styles after hover styles
> Fix active state styles

- app/server/migrations/20210131143432_update_groups_alert_only_on_failure.ts
- app/server/models/group.ts
- app/server/services/alert/send.ts
- app/server/types.ts
- app/test/server/models/group.test.ts
- app/test/server/services/alert/send.test.ts
> Add option to send alert only on failure in backend

- app/server/models/runner.ts
- app/test/server/models/runner.test.ts
- app/test/server/resolvers/runner.test.ts
> only expire runs in progress

- app/graphql/fragments.ts
- app/lib/types.ts
- app/server/migrations/20210205142752_update_tests_remove_url.ts
- app/server/models/test.ts
- app/server/resolvers/test.ts
- app/server/schema.graphql
- app/server/types.ts
- app/test/server/models/test.test.ts
- app/test/server/resolvers/test.test.ts
- app/test/server/utils.ts
> Do not store test URL in database

- app/hooks/mutations.ts
- app/server/migrations/20210209144226_update_triggers_remove_alert_settings.ts
- app/server/models/trigger.ts
- app/server/types.ts
- app/test/server/models/trigger.test.ts
- app/test/server/services/alert/send.test.ts
- app/test/server/utils.ts
> Remove alert settings from trigger

- app/components/Editor/Sidebar/Buttons.tsx
- app/components/Editor/Sidebar/index.tsx
- app/components/Editor/contexts/RunnerContext.tsx
- app/components/Editor/hooks/runProgress.ts
- app/components/Editor/hooks/runTest.ts
- app/components/shared-new/icons/Stop.tsx
- app/lib/runner.ts
- app/theme/copy.ts
- runner/src/environment/Environment.ts
- runner/src/environment/Run.ts
- runner/src/environment/VM.ts
- runner/src/environment/transformCode.ts
- runner/src/runner/Runner.ts
- runner/src/server/SocketServer.ts
- runner/test/environment/Environment.test.ts
- runner/test/environment/Run.test.ts
- runner/test/environment/VM.test.ts
- runner/test/environment/__snapshots__/transformCode.test.ts.snap
- runner/test/runner/Runner.test.ts
- runner/test/server/SocketServer.test.ts
> Stop a run

- app/components/Editor/Sidebar/RunLogs.tsx
> Scroll logs to the bottom

- app/server/services/alert/slack.ts
- app/test/server/services/alert/__snapshots__/slack.test.ts.snap
> Include fallback text for Slack alerts

- app/netlify.toml
- app/next.config.js
- app/package-lock.json
- app/package.json
- app/pages/api/graphql.ts
- app/server/context.ts
- app/server/services/alert/email.ts
Resolves https://github.com/qawolf/qawolf/issues/1021
> Add netlify

- .github/workflows/test_app.yml
- app/components/Editor/Sidebar/Buttons.tsx
- app/components/Editor/Sidebar/index.tsx
- app/lib/client.ts
- app/server/context.ts
- app/server/environment.ts
- app/test/server/context.test.ts
> Reload page if version out of date

- app/components/Editor/Header/RunSummary.tsx
- app/components/Editor/Header/index.tsx
- app/components/Editor/Sidebar/index.tsx
- app/components/Editor/contexts/RunnerContext.tsx
- app/components/Editor/contexts/TestContext.tsx
- app/components/Editor/helpers.ts
- app/components/Editor/hooks/env.ts
- app/components/shared-new/TriggerBadge.tsx
- app/graphql/queries.ts
- app/lib/types.ts
- app/server/resolvers/suite.ts
- app/server/schema.graphql
- app/test/server/resolvers/suite.test.ts
> Include suite environment when editing test

- app/server/models/run.ts
- app/test/server/models/run.test.ts
- app/test/server/utils.ts
> set up email environment for suites

- app/components/ConfirmEmail/CodeSegment.tsx
- recorder/src/isDynamic.ts
- recorder/test/isDynamic.test.ts
- recorder/test/selector.test.ts
- add data-test attribute to CodeSegment
> improve isDynamic a little

- app/pages/_document.tsx
- app/public/types.txt
- app/scripts/generateTypesFile.ts
- runner/src/environment/launch.ts
- runner/src/environment/trackingHosts.ts
> Block analytics tracking by default

- app/server/migrations/20210222130512_runs_error.ts
- app/server/models/run.ts
- app/server/models/runner.ts
- app/server/resolvers/run.ts
- app/server/resolvers/runner.ts
- app/server/schema.graphql
- app/server/types.ts
- app/test/server/models/run.test.ts
- app/test/server/models/runner.test.ts
- app/test/server/resolvers/run.test.ts
- app/test/server/resolvers/runner.test.ts
- runner/src/environment/VM.ts
- runner/src/runner/StatusReporterHook.ts
- runner/src/services/api.ts
- runner/src/services/aws.ts
- runner/test/runner/Runner.test.ts
> Retry runs with ERR_CONNECTION_REFUSED error

- app/server/api/github/deployment.ts
- app/server/migrations/20210222193011_update_teams_vercel_team.ts
- app/server/types.ts
- app/test/server/api/github/deployment.test.ts
> Option to build deployment URL based on branch name

- app/server/models/runner.ts
- app/test/server/models/runner.test.ts
Followup for https://github.com/qawolf/qawolf/pull/1073
> prevent assignRunner race condition

- app/server/api/github/deployment.ts
- app/test/server/api/github/deployment.test.ts
> Fix git branch url

- runner/src/services/Logger.ts
- runner/src/services/api.ts
- runner/src/services/inbox.ts
> simplify and expose logs to waitForEmail

- app/components/Dashboard/Sidebar/Groups.tsx
- app/components/Dashboard/Sidebar/Header.tsx
- app/components/Dashboard/Sidebar/index.tsx
- app/components/Dashboard/Tests/Header/index.tsx
- app/components/Dashboard/Tests/index.tsx
- app/components/Dashboard/index.tsx
- app/theme/copy.ts
* show group name in page header
* create test from group automatically adds it to that group
> Groups improvements

- app/.env.example
- app/components/Docs/Layout/Content.tsx
- app/components/Docs/Layout/Navigation/Buttons.tsx
- app/components/Docs/Layout/index.tsx
- app/components/shared-new/GitHubStars.tsx
- app/components/shared-new/Search.tsx
- app/hooks/algolia.ts
- app/pages/_document.tsx
- app/theme/global.css
> Add search to docs

- runner/package-lock.json
- runner/package.json
The label regression should be fixed in the next release
> downgrade pw to 1.8.1 to avoid 1.9 regression

- app/components/Editor/Sidebar/HelpersEditor.tsx
* ignore stale helpers updates
> Fix helpers

- app/components/Dashboard/Tests/List/index.tsx
- app/components/Dashboard/Tests/index.tsx
- app/components/shared/AppTextInput/index.tsx
- app/components/shared/TextInput.tsx
- app/pages/docs/create-a-test.mdx
- app/theme/theme.ts
* sometimes text input style is off, fix it
> Input style fixes

- app/pages/docs/launch.mdx
- runner/Dockerfile
- runner/src/environment/launch.ts
- runner/test/environment/launch.test.ts
> launch: add chrome option

- recorder/src/generateCueSets.ts
- recorder/test/generateSelectors.test.ts
Will probably rework batching soon
> Tweak selectors

- recorder/src/generateCueSets.ts
- recorder/src/getCues.ts
- recorder/src/isElementMatch.ts
- recorder/src/qawolf.ts
- recorder/test/getCues.test.ts
- recorder/test/isElementMatch.test.ts
> More selector improvements

- app/pages/docs/get-inbox.mdx
- app/public/types.txt
- app/scripts/generateTypesFile.ts
- app/server/migrations/20210404151128_update_emails_is_outbound.ts
- app/server/models/email.ts
- app/server/resolvers.ts
- app/server/resolvers/email.ts
- app/server/schema.graphql
- app/server/services/alert/email.ts
- app/server/services/sendgrid.ts
- app/server/types.ts
- app/test/server/models/email.test.ts
- app/test/server/resolvers/email.test.ts
- app/test/server/utils.ts
- runner/src/services/api.ts
- runner/src/services/inbox.ts
> Allow sending email from test accounts

- recorder/src/ElementChooserView.ts
- recorder/src/generateCueSets.ts
- recorder/src/getCues.ts
- recorder/src/isElementMatch.ts
- recorder/test/generateSelectors.test.ts
- recorder/test/isElementMatch.test.ts
> Exact match iframe

- app/graphql/fragments.ts
- app/hooks/mutations.ts
- app/lib/types.ts
- app/scripts/generateSystemEnvVariables.ts
- app/server/models/environment_variable.ts
- app/server/resolvers/test.ts
- app/server/schema.graphql
- app/server/services/location.ts
- app/server/types.ts
- app/shared/utils.ts
- app/test/server/resolvers/test.test.ts
- runner/src/code/patchEvent.ts
- runner/src/environment/Environment.ts
- runner/src/environment/Run.ts
- runner/src/types.ts
- runner/test/code/patchEvent.test.ts
- runner/test/code/patchReload.test.ts
- runner/test/environment/Run.test.ts
> No wait until

- app/pages/docs/run-tests-on-netlify-deployment.mdx
- app/server/api/netlify/suites.ts
* do not alert unless error is 500
* do not say Netlify UI is recommended
> Netlify tweaks

- app/components/Modals/Environments/Environments/index.tsx
- app/components/Modals/Environments/index.tsx
Fixes https://app.datadoghq.com/logs?agg_m=count&agg_t=count&from_ts=1618373417000&index=%2[…]vent=AQAAAXjOn8c_kfeg4QAAAABBWGpPbjlOd0FBRGJURkZFM2NWTnVRQUM
> Fix 500 when adding variable to first environment

- app/pages/docs/get-inbox.mdx
- app/public/types.txt
- app/scripts/generateTypesFile.ts
- runner/package-lock.json
- runner/package.json
- runner/src/services/inbox.ts
- runner/src/types.ts
> parse urls from email

- app/components/Editor/Sidebar/CodeEditor/index.tsx
- app/components/Editor/Sidebar/Editor.tsx
- app/components/Editor/Sidebar/HelpersEditor.tsx
- app/components/Editor/Sidebar/index.tsx
- resolves #1220
- replace #1221
> persist the position

- app/server/models/runner.ts
- app/test/server/models/runner.test.ts
sometimes aci can be slow to allocate containers
> increase healthy tolerance

- recorder/src/ActionRecorder.ts
- recorder/src/EventSequence.ts
- recorder/src/qawolf.ts
- recorder/src/resolveElementAction.ts
- recorder/src/types.ts
- recorder/test/ActionRecorder.test.ts
- recorder/test/fixtures/ActionRecorder.html
- recorder/test/fixtures/resolveElementAction.html
- recorder/test/resolveElementAction.test.ts
> Fix resolve action

- app/components/Dashboard/Suite/List/RunCard/Details.tsx
- app/components/Dashboard/Suite/List/RunCard/index.tsx
- app/components/shared/CheckBox.tsx
- app/components/shared/Meta.tsx
- app/package-lock.json
- app/pages/_document.tsx
- also make the run cards a bit nicer with long test names (more to do here but this is an improvement)
> Social card

- app/pages/docs/why-qa-wolf.mdx
Just fixes a misspell of "opinionated"
> fix typo in docs

- app/components/Editor/Header/TestButtons.tsx
- app/components/Editor/contexts/EditorController.ts
- app/components/Editor/hooks/editorController.ts
- app/hooks/mutations.ts
- app/lib/VersionedMap.ts
> fix saved values

- app/components/Dashboard/Tests/Header/Branches.tsx
- app/server/services/gitHub/branch.ts
- support choosing branch with query param
> Branch hotfix

- app/lib/client.ts
these can be caused by expired tokens etc
> do not show authentication errors to users

- app/server/api/github/deployment.ts
- app/server/migrations/20210515114431_remove_vercel_team.ts
- app/server/types.ts
- app/test/server/api/github/deployment.test.ts
This doesn't work all the time because we do not know the hashing algo vercel uses
> remove unused vercel_team

- app/components/Dashboard/Settings/Plan/Usage.tsx
- app/components/Docs/docs.ts
- app/components/Editor/Sidebar/Snippet/helpers.ts
- app/components/Editor/Sidebar/Snippet/index.tsx
- app/lib/helpers.ts
- app/pages/docs/create-a-test.mdx
- app/pages/docs/get-value.mdx
- app/pages/docs/globals.mdx
- app/pages/playground/editable-list.tsx
- app/pages/playground/form-inputs.tsx
- app/pages/playground/index.tsx
- app/pages/playground/log-in-updated.tsx
- app/pages/playground/log-in.tsx
- app/public/types.txt
- app/scripts/generateTypesFile.ts
- app/test/lib/helpers.test.ts
- app/theme/copy.ts
- qawolf/package-lock.json
- qawolf/package.json
- qawolf/src/api/assertText.ts
- qawolf/src/api/getValue.ts
- qawolf/src/api/index.ts
- qawolf/test/api/assertText.test.ts
- qawolf/test/api/getValue.test.ts
- recorder/src/element.ts
- runner/package-lock.json
- runner/package.json
- runner/src/environment/VM.ts
> getValue snippet

- app/components/Docs/docs.ts
- app/components/Editor/Sidebar/Snippet/Action.tsx
- app/components/Editor/contexts/TestContext.tsx
- app/pages/docs/get-a-value.mdx
- app/pages/playground/editable-list.tsx
- qawolf/package-lock.json
- qawolf/package.json
- qawolf/src/api/assertText.ts
- qawolf/test/api/assertText.test.ts
- runner/package-lock.json
- runner/package.json
> Allow text selectors in assertText

- app/pages/docs/run-tests-on-render-deployment.mdx
- app/server/api/github/deployment.ts
- app/server/migrations/20210521130402_update_triggers_render_environment.ts
- app/server/types.ts
- app/test/server/api/github/deployment.test.ts
> Filter out unused render deployments
