qawolf/qawolf

- packages/browser/src/Browser.ts
- packages/browser/src/QAWolfPage.ts
- packages/browser/src/RequestTracker.ts
- packages/browser/src/pageUtils.ts
- packages/browser/tests/RequestTracker.test.ts
Goal: Slim down Browser to make it more readable, create a home for managing the page
- separate findElement to pageUtil to slim down Browser
setup QAWolfPage:
- injects QAWolf library
- emulates the device
- manages waiting for requests
> setup QAWolfPage to manage page instead of Browser

- packages/browser/src/actions.ts
- packages/browser/src/find.ts
- packages/browser/tests/web/hasText.test.ts
- packages/browser/tests/web/wait.test.ts
- packages/jest-environment/src/RunnerEnvironment.ts
- packages/web/src/wait.ts
Fixes an issue where finding element after beforeAction sleep was not respecting timeout=0.
This caused test timeouts and slows down tests w/o strong matches.
> fix timeoutMs = 0

- packages/browser/tests/web/element.test.ts
- packages/web/src/element.ts
If a target is the descendant of a button/a/input we want to click the parent -- otherwise choose the target. This is to avoid the issue where a parent div does something different. Eg dropdown divs.
> do not choose non-common clickable element types

- packages/browser/tests/web/serialize.test.ts
- packages/web/src/serialize.ts
to prevent weird unicode characters for line breaks `can click "Sort flights by: &#10;Sort flights by dr..."`
> innertext: cleanText before setting as an attribute

- packages/browser/src/find/find.ts
- packages/browser/src/find/findHtml.ts
- packages/browser/src/find/findText.ts
- packages/browser/tests/Browser.test.ts
- packages/runner/src/Runner.ts
- packages/web/src/find/findText.ts
- Browser.find: retryExecutionError
- findText: use queryActionElements to only choose valid / visible elements
- Runner.beforeAction: if an element is not immediately found after sleep, look for it again with the findTimeout. eg. the page reloads in between the sleep
> Browser.find: retryExecutionError

- packages/browser/src/keyboard/index.ts
- packages/browser/src/keyboard/keys.ts
- packages/browser/src/keyboard/serializeStrokes.ts
- packages/browser/src/keyboard/simplifyStrokes.ts
- packages/browser/tests/keyboard/keys.test.ts
- packages/browser/tests/keyboard/serializeStrokes.test.ts
- packages/build-workflow/src/buildTypeSteps.ts
- packages/web-tests/tests/Recorder.test.ts
fixes #240
- remove characterToStrokes logic which made bad assumptions for non-us keyboards, this simplifies our keyboard code a lot
- instead use sendCharacter for single characters (we will add a little complexity to that in https://github.com/qawolf/qawolf/issues/242 to better support hotkeys)
> use sendCharacter for keys that are single characters

- bin/qawolf
- export DOCKER_HOST as an environment variable
This is to make it easy to run tests against localhost in GitHub Actions / etc. Resolves #265
> Docker: add docker-host to hosts

- README.md
I have referenced [this documentation](https://docs.qawolf.com/docs/quick_start#-create-a-browser-test).
> Fix 'Invalid command "create"' error in README.md

- packages/browser/src/browser/QAWolfBrowser.ts
- packages/cli/src/index.ts
- packages/qawolf/package-lock.json
#306
- alias "qawolf record"
- support selector.page for now
Now the only breaking change is the old data attribute logic (which is inlined in this release).
> Improve backwards compatibility with 0.7.0

- packages/cli/static/azure.hbs
- packages/cli/static/circleci.hbs
- packages/cli/static/github.hbs
- packages/cli/static/gitlab.hbs
- packages/qawolf/package-lock.json
#306 
- Use node directly instead of docker
- Include commented out example of starting node server
- Cache node_modules
> Update ci templates for 0.8.0

- docs/docs/cli.md
- docs/docs/run_a_test_locally.md
- docs/src/components/GetStarted.js
- packages/cli/src/create.ts
- packages/cli/src/index.ts
- packages/cli/src/runJest.ts
- packages/cli/src/utils.ts
- packages/cli/tests/runJest.test.ts
> feat(cli): Add path option

- docs/docs/api.md
- packages/browser/src/actions/clickElement.ts
- packages/browser/src/actions/index.ts
- packages/browser/src/browser/Browser.ts
- packages/browser/src/browser/QAWolfBrowser.ts
- packages/browser/src/page/QAWolfPage.ts
- packages/web-tests/tests/Recorder.test.ts
Default click to use HTMLElement.click with is more stable than ElementHandle.click. Provide option to `{ simulate: false }`.
Relates to https://github.com/puppeteer/puppeteer/issues/3347
> Simulate click by default

- packages/browser/src/actions/clickElement.ts
- packages/build-workflow/src/buildClickSteps.ts
- packages/test/events/click_username.json
- packages/test/events/dropdown.json
- packages/test/events/githubIssuesShortcut.json
- packages/test/events/scroll_login.json
- packages/test/events/selectall.json
- packages/test/events/threePages.json
- packages/types/src/event.ts
- packages/web-tests/tests/Recorder.test.ts
- packages/web-tests/tests/format.test.ts
- packages/web/src/Recorder.ts
- packages/web/src/element.ts
- packages/web/src/format.ts
Clicking on the Material UI dropdown (with native set to false) would create code for clicking on the body #418. This is because it oddly emits the click on the body instead of the element. 
- Changed the Recorder to listen for mousedown instead and the target is correct. This is most likely since it happens right away (we use capture: true in our listener).
- Reverted click to use Playwright click by default, and simulate is hidden behind the option. I go back and forth on simulating clicks or not, however I think we should prefer things closer to Playwright API when possible. When people have issues with click they can report a bug to Playwright and switch the option to simulate. Relates to #334.
To Do
Resolves #418
> 🖱️Record mousedown instead of click. Use Playwright click by default.

- src/cli/cli.ts
Easier to only have one way to do things: "npm init qawolf" / "yarn create qawolf"
> remove `npx qawolf ci`

- docs/docs/create_a_test.mdx
- docs/docs/edit_a_test.md
- src/create-code/CodeUpdater.ts
- src/create-code/create.ts
- src/create-code/patchCode.ts
- test/create-code/CodeFileUpdater.test.ts
- test/create-code/__snapshots__/CodeFileUpdater.test.ts.snap
- test/create-code/__snapshots__/CodeReconciler.test.ts.snap
Resolves #674 
Replaces #612
Use  "// 🐺 create code here" instead of `await qawolf.create();`. This is more obvious and resolves issues with formatting
> Use a comment as the patch handle

- packages/create-qawolf/static/github.yml
> Fix ci template

- src/web/cues.ts
A fix for the "secondary issue" described in https://github.com/qawolf/qawolf/issues/737
In addition to `data-testid` attributes, now `data-test-id` and any other attribute beginning with `data-test` will be preferred when using the default QA Wolf configuration.
> fix: use any data-test* for selector

- package-lock.json
- package.json
- packages/sandbox/package-lock.json
- packages/sandbox/package.json
- packages/sandbox/src/pages/Buttons/HtmlButtons.js
- src/web/isDynamic.ts
- test/web/isDynamic.test.ts
- test/web/selector.test.ts
* The class `StyledLayer-rmtehz-0` was not marked as dynamic, because the `0` at the end was filtered out from the tokens array
* By including it, `isDynamic` is more stringent, which I think is OK (better to be safe than sorry)
* Affected one test case: `btn-b` is currently not considered dynamic, but with this change it will be
> Make isDynamic more stringent on trailing characters

- src/build-code/buildStepLines.ts
I had timing problems clicking a button in an iframe:
```
~/D/N/QaWolf $ npx qawolf test myFirstTest
Test: chromium
npx jest --config="node_modules/qawolf/js-jest.config.json" --rootDir=.qawolf --testTimeout=60000 myFirstTest
FAIL  .qawolf/myFirstTest.test.js (5.019 s)
✕ myFirstTest (3929 ms)
● myFirstTest
TypeError: Cannot read property 'contentFrame' of null
20 |   await page.click(".clickable .clickable");
21 |   await page.click('[href="/WebApp/Open/ScannerSim/"]');
> 22 |   const frame = await (await page.$("#sim")).contentFrame();
|                                              ^
23 |   await frame.click(".nav-button");
24 | });
25 | 
at Object.test (myFirstTest.test.js:22:46)
Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.401 s, …
```
> Use waiting selector method instead of $ method to get iframe handle

- src/web/selectorEngine.ts
- src/web/types.ts
- src/web/webpack.config.js
Resolves #799
Use querySelector instead of querySelectorAll. This cuts trimExcessCues to ~200ms instead of many seconds on the expensive search input cues. We can rank and limit the initial cue list size as well if we run into a worse case.
> fix: speed up selector generation

- package-lock.json
- package.json
- packages/sandbox/package-lock.json
- packages/sandbox/package.json
- packages/sandbox/src/pages/TextInputs/HtmlTextInputs.js
- src/web/PageEventCollector.ts
- src/web/element.ts
- src/web/qawolf.ts
- test/web/element.test.ts
- Create `getInputElementValue` function with adjusted logic
- Create tests for it
Fixes #801. Refer to the problem description [here](https://github.com/qawolf/qawolf/issues/801#issuecomment-683141690)
> fix: fill correct value for contenteditable inputs

- src/build-code/buildStepLines.ts
- src/build-code/buildVirtualCode.ts
- test/build-code/buildStepLines.test.ts
Resolves #798 
If there are multiple pages, we generate multiple page variables in the output. For example, `page`, then `page2`, then `page3`, etc. After that, Playwright actions happen on certain pages (or frames). So we might have `page.fill(...)` followed by `page2.click(...)`, and so on.
When we go from one acting on one page to acting on another page, and that second page is already initialized/loaded, that page stays in the background. This means the running test isn't visible if watching it run or recording a video.
Call `${pageVariable}.bringToFront` each time before running an action on an existing page, when the previous action was not on that page.
1. Find any website where there are a number of links that have target `_blank` (automatically open in a new tab).
2. Do …
> feat: bring page to front before acting on it

- package-lock.json
- package.json
- packages/sandbox/package-lock.json
- packages/sandbox/package.json
- packages/sandbox/src/pages/Buttons/HtmlButtons.js
- src/web/PageEventCollector.ts
- src/web/cues.ts
- src/web/element.ts
- src/web/optimizeCues.ts
- src/web/qawolf.ts
- src/web/selector.ts
- test/web/element.test.ts
- test/web/selector.test.ts
Resolves #795 
Previously, for "click" events, the generated selector would target the topmost element in the clickable group. For example, if "click" is received for `button > span > i` element, the selector would be generated for that `button`.
However, sometimes the original target or one of the in-between elements has a better attribute for selection. For example, maybe one of them has a `data-qa` attribute.
Now, all elements in the clickable group are considered when generating a selector, and the one with the lowest penalty will be used.
1. Run sandbox website in this branch.
2. `DEBUG=qawolf:* qawolf create http://localhost:5000/buttons`
3. Click the "Better attribute on span" button
4. Verify that `await page.click('text="Better attribute on span"');` line is added to the …
> Fix click selector penalties

- package-lock.json
- package.json
- packages/sandbox/package-lock.json
- packages/sandbox/package.json
- packages/sandbox/src/pages/Buttons/HtmlButtons.js
- src/web/PageEventCollector.ts
- src/web/cues.ts
- src/web/element.ts
- src/web/optimizeCues.ts
- src/web/qawolf.ts
- src/web/selector.ts
- test/web/element.test.ts
- test/web/optimizeCues.test.ts
- test/web/selector.test.ts
Resolves #827 
When finding the nicest selector for a click event:
- Other descendants of the topmost clickable element will be considered, even if they are not ancestors of the original click `target`. This currently goes to a maximum depth of 10 elements down from the topmost element
- `svg` elements will be considered but none of their descendants are considered because there could be many
- There is a boundary between clickable groups nested within other clickable groups. For example, if there is an `<a>` within a `<button>` and you click on the `<button>` outside of the `<a>`, neither the `<a>` nor any of its descendants are considered as possible selectors for the click event. Conversely, if you click on the `<button>` within the `<a>`, then the `<a>` and all its descendants are …
> fix: handle more nested button group cases

- package-lock.json
- package.json
- packages/sandbox/package-lock.json
- packages/sandbox/package.json
- packages/sandbox/src/pages/CheckboxInputs/HtmlCheckboxInputs.js
- src/web/cues.ts
- src/web/isDynamic.ts
- test/web/cues.test.ts
- test/web/isDynamic.test.ts
Resolves #829 
When building cues for an element, attributes that have a value that is either an empty string or appears to be dynamic (machine-generated) are now not used as cues. There are two exceptions: `href` and `src` which would frequently have dynamic values as part of the URL. Other attributes can be made exempt if you can think of reasons, or we could try to make `isDynamic` smarter.
Note that currently a half-dynamic value such as `input-d8sdgjk3` will be used. This is up for debate.
**Update**
Above is the original description, but here's how this actually works at the point of merging it.
- I left `isDynamic` pretty much the same
- But instead of running attribute values through `isDynamic`, I created a new function `getValueMatches` that attempts to find all the static …
> feat: ignore some dynamic-value attributes

- src/web/cues.ts
- src/web/element.ts
- src/web/optimizeCues.ts
- src/web/selector.ts
- src/web/selectorEngine.ts
- test/web/cues.test.ts
- Fixes an issue that prevented cached selectors from being used when the chosen selector is a part of a click group and not the original target.
- On a click, this roughly cuts in half the amount of time it takes to add the click step because the `click` event can reuse the selector built for the nearly simultaneous `mousedown`
- Reduces the number of loops and consolidates some handling for `buildCues` and `optimizeCues`
- One big help was: in `findBestCueGroup`, now uses `getElementMatchingSelectorParts` and `targetGroup.includes` rather than running `isMatch` multiple times.
- On a click, this roughly reduces the amount of time it takes to add the click step by a factor equal to the number of elements in the click group. For example, a click group that has 4 elements and previously …
> Refactor buildSelector to be speedier

- src/cli/cli.ts
From [v5.0.0](https://github.com/tj/commander.js/releases/tag/v5.0.0), Commander.js displays an error message for a missing subcommand by default.
> remove stale code

- docs/docs/install.mdx
- "the" CLI doesn't make sense, as we don't specify _which_ CLI is it. Is it the QA Wolf CLI? Your system's CLI e.g bash or zsh? 
- Using "a" CLI, it's clear what we mean: the QA Wolf CLI
- On line 29 however, it makes perfect sense as we specify _which._
> docs: update install.mdx

- app/server/models/runner.ts
- app/server/models/test.ts
- app/server/resolvers/runner.ts
- app/test/server/models/runner.test.ts
- app/test/server/models/test.test.ts
- merge findRunner into one query to reduce db queries
- do not mark runner_requested_at when there is a runner assigned (this can happen during a concurrent assignment)
Relates to #912
> Do not mark test as pending if it already assigned

- app/components/Editor/Placeholder.tsx
- app/components/Editor/Screencast.tsx
- app/components/Editor/contexts/RunnerContext.tsx
- app/components/Editor/hooks/browser.ts
- app/components/Editor/hooks/connectRunner.ts
- app/components/Editor/hooks/runTest.ts
- app/lib/runner.ts
Relates to #912
Fixes an issue if it takes longer to connect then the reconnect cycle allows
- remove framebufferupdate patch, we probably cannot trust this so just rely on connected as our ready signal
- rename isIdle to shouldRequestRunner for consistency
- disconnect runner client when the runner is null
> only reconnect browser on disconnect

- recorder/src/resolveAction.ts
- recorder/test/resolveAction.test.ts
If a dropdown closes on mousedown before the click event is fired and we resolve the action, we still want to create code for the click.
This *could* create extra code a user does not want however they could always delete it. However I cannot think of a scenario where this would be the case off the top of my head.
> Allow emitting actions for invisible targets

- app/components/Editor/Canvas/Placeholder.tsx
I added an assertion to our e2e test for this.
Broken commit: https://github.com/qawolf/qawolf/commit/e115d8e1b6d1cf9aadb5f31b24050931af376168
> Do not show loading incorrectly

- app/server/jobs/orchestrateRunners.ts
- app/server/jobs/restartRunners.ts
- app/server/migrations/20210223110740_tests_not_deleted_and_runner_requested_at.ts
- app/server/models/run.ts
- app/server/models/runner.ts
- app/server/models/test.ts
- app/server/resolvers/run.ts
- app/test/server/jobs/orchestrateRunners.test.ts
- app/test/server/models/run.test.ts
- app/test/server/models/runner.test.ts
- app/test/server/models/test.test.ts
- app/test/server/resolvers/run.test.ts
- app/test/server/resolvers/runner.test.ts
- app/test/server/utils.ts
Resolves #1071 
- Include in progress tests and runs in pool calculations
- Fix a potential race condition where an assigned runners could be deleted during rebalancing
- Retry in progress runs for deleted unhealthy runners once
- Alert us to unhealthy runners
- Add db constraint to ensure tests are not pending after deleted
- Consolidated reset runner logic (delete, expire, restart)
> pool: consider incomplete runs

- app/components/Modals/Triggers/CreateOrEditTrigger/Form.tsx
- app/server/models/team.ts
- app/test/server/models/team.test.ts
- app/test/server/resolvers/user.test.ts
* Fix 🐛: Do not show environment as selected in edit trigger modal if not assigned to trigger
* Create an environment on sign up to avoid step of having to create one
> Create environment on sign up

- runner/src/environment/launch.ts
- runner/test/environment/launch.test.ts
This feature from playwright 1.10 auto-handles the executablePath
> use chrome channel for chrome

- app/components/Editor/Canvas/Placeholder.tsx
- app/components/Editor/contexts/RunnerContext.tsx
- app/components/Editor/hooks/connectRunner.ts
- app/components/Editor/hooks/runTest.ts
- app/graphql/queries.ts
- app/hooks/queries.ts
- app/server/models/runner.ts
- app/server/resolvers/runner.ts
- app/server/schema.graphql
- app/test/server/models/runner.test.ts
- app/test/server/resolvers/runner.test.ts
- rename should_request_runner -> request_test_runner
- if request_test_runner is provided, only return a test runner
- return a run runner when only run_id is provided to runner query
> Clearly delineate when to return a run vs test runner

- app/.dockerignore
- app/.env.example
- app/Dockerfile
- app/next.config.js
- app/scripts/docker-entrypoint.sh
- docker-compose.yml
- runner/.dockerignore
- runner/Dockerfile
- runner/Dockerfile.base
- runner/scripts/entrypoint.sh
- runner/scripts/nginx.sh
- runner/scripts/supervisord.conf
- wolf
The updates/changes...
- Dockerize the NextJS app
- set a dedicated location for `WORKDIR` in the runner build so that files aren't all mixed in with root OS dirs in the container
- updated entrypoint script for the runner container
- created a bash CLI script for most common dev env tasks
Since the script help message is fairly self explanatory, here's the summary...
```
./wolf help
Usage:
./wolf [OPTION]
Options:
init      Install deps in all projects, build the runner container, and run app migrations
build     Build all containers (or specify a container to build with an additional argument)
dev       Start postgres and runner containers, then start app in dev mode
start     Run production builds in docker containers and tail logs app/runner logs
stop      Stop all running containers …
```
> create bash CLI script for most common dev env tasks

- app/server/models/test.ts
- app/test/server/models/test.test.ts
The `NOT IN (SELECT test_id FROM runners)` clause does not work as expected when some of the records have a null `test_id`.
There are numerous SOs about this such as https://stackoverflow.com/questions/19517899/not-in-in-postgresql-not-working
The effect of this bug for me locally was that `app` would repeatedly log the `skipped` message when attempting `updateTestToPending` and the test editor would spin indefinitely. It's unclear whether this ever happens in the prod setup.
Update to `(id IN (SELECT test_id FROM runners)) IS NOT TRUE`, which handles it being either FALSE or NULL.
> fix: NOT IN issue setting test to pending

- app/components/Docs/SuiteApiExample.tsx
Spelling correction to route endpoint that may have driven me crazy for 30 mins because I was copy pasting it.
> Corrected Misspelling in SuiteApiExample.tsx

- app/components/Modals/CreateTest.tsx
- app/lib/helpers.ts
- app/test/lib/helpers.test.ts
* before, URLs like `login` were considered valid. now they are not
> Fix URL validation
